[devenv]
minimum_version = 1.14.2

[gcloud]
# used for autoupdate
version = 540.0.0
# custom python version not supported yet, it just uses
# devenv's internal python 3.11
# python = 3.11.6
darwin_x86_64 = https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-540.0.0-darwin-x86_64.tar.gz
darwin_x86_64_sha256 = 5b52fca721979d371c083f99463cf4b8f36d42f5d10fcb2381ffaf13536a2c98
darwin_arm64 = https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-540.0.0-darwin-arm.tar.gz
darwin_arm64_sha256 = d7af233c272ef0a422db75e42be0cbd11f8a9af3a6da11b4b46278c6a399fda4
linux_x86_64 = https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-540.0.0-linux-x86_64.tar.gz
linux_x86_64_sha256 = fe04996f26a8ccd1a7aab326618a0992e769c8e86deabce544905d24ccd47014

[uv]
darwin_arm64 = https://github.com/astral-sh/uv/releases/download/0.8.2/uv-aarch64-apple-darwin.tar.gz
darwin_arm64_sha256 = 954d24634d5f37fa26c7af75eb79893d11623fc81b4de4b82d60d1ade4bfca22
darwin_x86_64 = https://github.com/astral-sh/uv/releases/download/0.8.2/uv-x86_64-apple-darwin.tar.gz
darwin_x86_64_sha256 = ae755df53c8c2c1f3dfbee6e3d2e00be0dfbc9c9b4bdffdb040b96f43678b7ce
linux_arm64 = https://github.com/astral-sh/uv/releases/download/0.8.2/uv-aarch64-unknown-linux-gnu.tar.gz
linux_arm64_sha256 = 27da35ef54e9131c2e305de67dd59a07c19257882c6b1f3cf4d8d5fbb8eaf4ca
linux_x86_64 = https://github.com/astral-sh/uv/releases/download/0.8.2/uv-x86_64-unknown-linux-gnu.tar.gz
linux_x86_64_sha256 = 6dcb28a541868a455aefb2e8d4a1283dd6bf888605a2db710f0530cec888b0ad
# used for autoupdate
version = 0.8.2
