---
all:
  children:
    loadtest:
      children:
        master:
          hosts:
            mark-load-test-master:
              ansible_host: 34.11.148.114
        workers:
          hosts:
            # Add worker hosts here as they are provisioned
            # Example:
            # worker-01:
            #   ansible_host: 34.11.148.115
            # worker-02:
            #   ansible_host: 34.11.148.116

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_python_interpreter: /usr/bin/python3
