---
all:
  children:
    loadtest:
      children:
        master:
          hosts:
            mark-load-test-master:
              ansible_host: mark-load-test-master
              host_ip: 34.11.148.114
        workers:
          hosts:
            mark-load-test-worker-1:
              ansible_host: mark-load-test-worker-1
              host_ip: 34.145.12.55
            mark-load-test-worker-2:
              ansible_host: mark-load-test-worker-2
              host_ip: 34.169.82.177
            mark-load-test-worker-3a:
              ansible_host: mark-load-test-worker-3a
              host_ip: 34.83.86.248

  vars:
    # ansible_user: "{{ lookup('env', 'USER') }}"
    ansible_user: "mark_sentry_io"
    ansible_python_interpreter: /usr/bin/python3
