# Config file for fake sentry

# host ip for the server
host: 127.0.0.1
# port for the running server
port: 8000
# security key
key: "31a5a894b4524f74a9a8d0e27e21ba91"
# logging configuration
log:
  version: 1
  formatters:
    default:
      format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  handlers:
    console_logging:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: default
  loggers:
    werkzeug:  # infrastructure logger
      # DEBUG INFO WARNING ERROR CRITICAL
      level: WARNING
      propagate: false
      handlers:
        - console_logging
    fake_sentry.fake_sentry: # flask app logger
      level: DEBUG
      propagate: false
      handlers:
        - console_logging
  root: # general logger
    level: ERROR
    handlers:
      - console_logging
