# Config file for the load tester

use_fake_projects: true
relay:
  host: http://127.0.0.1
  port: 3000
kafka:
  broker:
    bootstrap.servers: "127.0.0.1:9092"
  topics:
    outcomes: outcomes
    events: ingest-events
    transactions: ingest-transactions
    attachments: ingest-attachments
    sessions: ingest-sessions

fake_projects:
  enable_metrics_extraction: false
projects:
  #list here all the valid projects with their public keys (not used in fake_sentry mode)
  - id: 1
    key: "31a5a894b4524f74a9a8d0e27e21ba91"
metrics:
  enabled: true

  influxdb:
    url: "http://localhost:8086"
    # TODO replace with some valid API token
    token: "48NlqRlitvNL1k322be_mPHru-qqjcmqjPLqOzOeVJwwep8bnpne2hOu6-NUY_FmxHKcU786QCUrEy0rFxPXFA=="
    # or set the token in an env variable
    # token: "${INFLUX_DB_API_TOKEN}"
    org: "sentry"
    bucket: "locust"

  default_tags:
#    some-tag: some-id
#    another-tag: hello


